### ISSUE TITLE
SSL SelfSigned problem

### ISSUE THREAD

**Issue by ETmanwenhan** [pedrovereza/SelfSignedMoya#2]
I follow your method, why does the following error message appear?

> Moya_Logger: [17/11/2017 16:23:06] Request: https://app200.yiban1314.com/msg/rule
> Moya_Logger: [17/11/2017 16:23:06] Request Headers: ["Content-Type": "application/x-www-form-urlencoded; charset=utf-8"]
> Moya_Logger: [17/11/2017 16:23:06] HTTP Request Method: POST
> Moya_Logger: [17/11/2017 16:23:06] Request Body: channel=007&platform_info=iPhone8&platform_type=2&sign=9ba4b6a6f3e203ecc95491f777e73c59&timestamp=1510906986314&to_user_id=2&user_id=2&version_id=001
> 2017-11-17 16:23:06.483908+0800 yiyue[56924:3437969] CredStore - copyIdentPrefs - Error copying Identity cred.  Error=-25300, query={
>     class = idnt;
>     labl = "https://app200.yiban1314.com:443/";
>     "r_Ref" = 1;
> }
> Moya_Logger: [17/11/2017 16:23:06] Response: Received empty network response for MsgRule("2").

```swift
 func msgRule() {
        
        let manager = Manager(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: CustomServerTrustPoliceManager()
        )
        
        let rxProvider = MoyaProvider<UserAPI>(manager: manager,
                                               plugins: [NetworkLoggerPlugin(verbose: true)])
        rxProvider.rx.request(.MsgRule(to_user_id:"2"))
            .debug()
            .mapJSON()
            .subscribe { event in
                
                switch event {
                case let .success(response):
                    debugPrint(response)
                    break
                case let .error(error):
                    print(error)
                    break
                }
        }
    }


class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return .disableEvaluation
    }
    public init() {
        super.init(policies: [:])
    }
}

```

**Comment by ETmanwenhan** [comment]
@pedrovereza 
Instantiate Manager, but it's still wrong. How to do?

> 2017-11-17 17:26:51.968639+0800 yiyue[59453:3754730] CredStore - copyIdentPrefs - Error copying Identity cred.  Error=-25300, query={
>     class = idnt;
>     labl = "https://app200.yiban1314.com:443/";
>     "r_Ref" = 1;
> }
> Moya_Logger: [17/11/2017 17:26:52] Response: Received empty network response for MsgRule("2").
> underlying(Alamofire.AFError.responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(400)), Optional(Status Code: 400, Data Length: 238))
> 

```swift
func msgRule() {
        
        // 确保项目已经成功导入了cert.cer证书文件
        let pathToCert = Bundle.main.path(forResource: "server", ofType: "cer")
        let localCertificate = NSData(contentsOfFile: pathToCert!)
        let certificates = [SecCertificateCreateWithData(nil, localCertificate!)!]
        
        let serverTrustPolicy = ServerTrustPolicy.pinCertificates(
            certificates: certificates,
            validateCertificateChain: false,
            validateHost: false
        )
        let serverTrustPolicies = ["app200.yiban1314.com" : serverTrustPolicy]
        let serverTrustPolicyManager = ServerTrustPolicyManager(policies: serverTrustPolicies)
        
        let manager = Manager(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: serverTrustPolicyManager
        )
        

        let rxProvider = MoyaProvider<UserAPI>(manager: manager,
                                               plugins: [NetworkLoggerPlugin(verbose: true)])
        rxProvider.rx.request(.MsgRule(to_user_id:"2"))
            .debug()
            .mapJSON()
            .subscribe { event in
                
                switch event {
                case let .success(response):
                    debugPrint(response)
                    break
                case let .error(error):
                    print(error)
                    break
                }
        }
```

**Comment by pedrovereza** [comment]
Hey @ETmanwenhan, sorry for the late response.

From your second comment, you're getting status code `400` back, that's not a SSL issue 😉

**Comment by ETmanwenhan** [comment]
I had solve the problem! Thank you!

**Comment by pedrovereza** [comment]
Great!
