### ISSUE TITLE
can't connect to localhost

### ISSUE THREAD

**Issue by MasterSwift** [pedrovereza/SelfSignedMoya#3]
hey , I was following tutorial on moya and tried doing testing on localhost where things didnt work out. So i checked this repo and replicated it but still getting the error 

`underlying(Error` Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x6040002552d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://localhost:8181/api/v1/people, NSErrorFailingURLStringKey=https://localhost:8181/api/v1/people, _kCFStreamErrorDomainKey=3}, `nil)`

struct NetworkAdapter {
    
    static let manager: Manager = {
        let serverTrustPolicies: [String: ServerTrustPolicy] = [
            "localhost:8181": ServerTrustPolicy.disableEvaluation
        ]
        
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders
        
        return Alamofire.SessionManager(configuration: configuration,
                                 serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
    }()
    
    static let provider = MoyaProvider<MyServerAPI>(manager: manager,
                                               plugins: [NetworkLoggerPlugin(verbose: true)])

    static func request(target: MyServerAPI, success successCallback: @escaping (Response) -> Void, error errorCallback: @escaping (Swift.Error) -> Void, failure failureCallback: @escaping (MoyaError) -> Void) {
        
        NetworkAdapter.provider.request(target) { (result) in
            switch result {
            case .success(let response):
                // 1:
                print(response)
                
            case .failure(let error):
                // 3:
                print(error)
            }
        }
    }
}

// 1:
enum MyServerAPI {
    
    // MARK: - Cameras
    case cameras
    case settingsFor(cameraId: String)
    
    // MARK: - User
    case createUser(email: String, password: String)
    case getUsers

}

// 2:
extension MyServerAPI: TargetType {
   
    
    // 3:
    var baseURL: URL { return URL(string: "https://localhost:8181")! }
    
    // 4:
    var path: String {
        switch self {
        case .cameras:
            return "/cameras"
        case .settingsFor(let cameraId):
            return "/cameras/\(cameraId)/settings"
        case .createUser:
            return "/user"
        case .getUsers:
            return "/api/v1/people"
        }
    }
    
    // 5:
    var method: Moya.Method {
        switch self {
        case .createUser:
            return .post
        default:
            return .get
        }
    }
    
    // 6:
    var parameters: [String: Any]? {
        switch self {
        case .createUser(let email, let password):
            var parameters = [String: Any]()
            parameters["email"] = email
            parameters["password"] = password
            return parameters
        default:
            return nil
        }
    }
    
    // 7:
    var parameterEncoding: ParameterEncoding {
        return JSONEncoding.default
    }
    
    // 8:
    var sampleData: Data {
        return Data()
    }
    
    // 9:
    var task: Task {
        return .requestPlain
    }
    
    //10.
    var headers: [String : String]? {
        return nil
    }
    
}

my info.plist also allows arbitrary loads. and I used the static provider in my NetworkAdapter class to make the 'get' call in my view controller.

**Comment by pedrovereza** [comment]
Hey @MasterSwift, have you tried disabling evaluation for all hosts? That's what `CustomServerTrustPoliceManager` does:

```swift
class CustomServerTrustPoliceManager : ServerTrustPolicyManager {
    override func serverTrustPolicy(forHost host: String) -> ServerTrustPolicy? {
        return .disableEvaluation
    }
    public init() {
        super.init(policies: [:])
    }
```

**Comment by freemansion** [comment]
confirming - couldn't access to `https://localhost:8000` using self-signed certificate.
Here is the log:
>Moya_Logger: [23/07/2018 23:19:47] Request: https://localhost/
Moya_Logger: [23/07/2018 23:19:47] Request Headers: [:]
Moya_Logger: [23/07/2018 23:19:47] HTTP Request Method: GET
2018-07-23 23:19:47.139814+0700 SelfSignedMoya[56090:39537273] [BoringSSL] Function nw_protocol_boringssl_handshake_negotiate_proceed: line 384 Handshake failed. Disconnecting the session
2018-07-23 23:19:47.160116+0700 SelfSignedMoya[56090:39537273] TIC TCP Conn Failed [1:0x604000163000]: 1:61 Err(61)
2018-07-23 23:19:47.161219+0700 SelfSignedMoya[56090:39537273] Task <16C99286-CD8F-44CB-9CFA-F1DE47AE6249>.<1> HTTP load failed (error code: -1004 [1:61])
2018-07-23 23:19:47.162184+0700 SelfSignedMoya[56090:39537275] Task <16C99286-CD8F-44CB-9CFA-F1DE47AE6249>.<1> finished with error - code: -1004
Moya_Logger: [23/07/2018 23:19:47] Response: Received empty network response for example.

**Comment by pedrovereza** [comment]
@freemansion have you tried `https://localhost:443` instead? By convention, port 443 is normally used for HTTPS.

**Comment by freemansion** [comment]
@pedrovereza Just solved. I'm using `django-sslserver` for setting up https on my localhost. The problem was that self-signed cert provided by tool above haven't been added to keychain. Thanks for quick reply!
